### ISSUE TITLE
To toolbars

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-geokoderen#2]
Pluginnet opretter to toolbars, hvoraf den ene er tom. Se i øvrigt også #1 
![image](https://cloud.githubusercontent.com/assets/1392735/11143487/d57e246c-89f5-11e5-8177-67758556c3a7.png)

**Comment by Telling** [comment]
Tak @AsgerPetersen. Både #1 og #2 er løst nu.
