### ISSUE TITLE
Crash ved load af plugin

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-geokoderen#3]
Min QGIS er begyndt at smide en exception. Tilsyneladende når geokoderen loades. Tilsyneladende noget med xlrd.

![image](https://cloud.githubusercontent.com/assets/1392735/12608394/2ce13bb0-c4dc-11e5-8f05-b10e7a5eceb6.png)

**Comment by Telling** [comment]
Var ikke geokoderen qgis plugin, men en anden `geokoder.py`. Lukker issue.
